workspace:
  base: /test
  path: ssk

pipeline:

  get-sanitzed-dump:
    image: fpfis/drone-plugin-asda
    target: dump.sql
    website: joinup/dumps
    secrets: [ asda_url ]
    when:
      event: push
      branch: [ master, release/* ]

  upload-build:
    image: drillster/drone-rsync 
    hosts: [ 10.0.110.23 ]
    user: web_asda
    secrets: 
      - source: key
        target: plugin_key
    source: dump.sql
    target: /web/content/asda/web/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME%%-reference}/builds/dump-${DRONE_COMMIT_SHA}.sql
    when:
      event: push
      branch: [ master, release/* ]
