workspace:
  base: /test
  path: ssk

pipeline:

  get-sanitzed-dump:
    image: fpfis/drone-plugin-asda
    target: dump.sql
    website: joinup/dumps
    secrets: [ asda_url ]
    when:
      event: push
      branch: [ master, release/* ]

  download-build:
    image: fpfis/php71-build
    commands:
      - wget 'https://github.com/ec-europa/platform-deploy/archive/2.5.0.tar.gz' -O release.tar.gz
      
  upload-build:
    image: appleboy/drone-sftp-cache
    server: 10.0.110.23
    port: 22
    username: web_asda
    secrets: [ key ]
    key: "$key"
    path: /web/content/asda
    ignore_branch: true
    when:
      event: push
      branch: [ master, release/* ]
      
