workspace:
  base: /test
  path: ssk

pipeline:

  get-sanitzed-dump:
    image: fpfis/drone-plugin-asda
    target: dump.sql
    website: joinup/dumps
    secrets: [ asda_url ]
    when:
      event: push
      branch: [ master, release/* ]

  upload-build:
    image: appleboy/drone-scp
    host: 10.0.110.23
    port: 22
    username: web_asda
    secrets: 
      - source: key
        target: ssh_key
    source: dump.sql
    target: /web/content/asda/web/joinup/builds
    when:
      event: push
      branch: [ master, release/* ]
