workspace:
  base: /test
  path: ssk

pipeline:

  get-sanitzed-dump:
    image: fpfis/drone-plugin-asda
    target: dump.sql
    website: joinup/dumps
    secrets: [ asda_url ]
    when:
      event: push
      branch: [ master, release/* ]

  download-pt:
    image: fpfis/php56-dev
    commands:
      - wget https://github.com/ec-europa/platform-deploy/archive/release-2.5.tar.gz -O release-${DRONE_COMMIT_SHA}.tar.gz

  upload-build:
    image: drillster/drone-rsync 
    user: web_asda
    secrets: [ plugin_key, plugin_hosts ]
    source: ./release-*.tar.gz
    target: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME%%-reference}/builds/
    when:
      event: push
