workspace:
  base: /test
  path: ssk

pipeline:

  get-sanitzed-dump:
    image: fpfis/drone-plugin-asda
    target: dump.sql
    website: joinup/dumps
    secrets: [ asda_url ]
    when:
      event: push
      branch: [ master, release/* ]

  upload-build:
    image: drillster/drone-rsync
    secrets: [ PLUGIN_KEY ]
    user: web_asda
    hosts: [ 10.0.110.23 ]
    port: 22
    source: dump.sql
    target: /web/content/asda/current/joinup/dumps/dump-${DRONE_COMMIT_SHA}.sql
    delete: true
    recursive: false
    when:
      event: push
      branch: [ master, release/* ]
