workspace:
  base: /test
  path: ssk

pipeline:

  get-sanitzed-dump:
    image: fpfis/drone-plugin-asda
    target: dump.sql
    website: joinup/dumps
    secrets: [ asda_url ]
    when:
      event: push
      branch: [ master, release/* ]

  upload-build:
    image: drillster/drone-rsync
    secrets: [ PLUGIN_KEY ]
    user: web_asda
    hosts: [ 10.0.110.23 ]
    source: dump.sql
    target: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME%%-reference}/builds/dump-${DRONE_COMMIT_SHA}.sql
    exclude: [ ".git" ]
    delete: true
    recursive: false
    when:
      event: push
      branch: [ master, release/* ]
