workspace:
  base: /test
  path: ssk

pipeline:

  get-sanitzed-dump:
    image: fpfis/drone-plugin-asda
    target: dump.sql
    website: joinup/dumps
    secrets: [ asda_url ]
    when:
      event: push
      branch: [ master, release/* ]
      
  download-build:
    image: appleboy/drone-scp
    host: 10.0.110.23
    username: web_asda
    secrets: [ ssh_key ]
    port: 22
    target: /web/content/asda/web/joinup/builds/
    source: release.tar.gz
    when:
      event: push
      branch: [ master, release/* ]
      
